rvm:
 - 2.2.2
 - 2.3.4
 - 2.4.1
install:
  - 'travis_retry bundle install'
script: 'bundle exec rspec spec'
gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
# Move to containerized travis, see http://docs.travis-ci.com/user/migrating-from-legacy
sudo: false
